### ISSUE TITLE
Could not compile depency socket2

### ISSUE THREAD

**Issue by Merrick17** [orao-network/solana-vrf#12]
Hello when I try to compile my project I get an error on compiling socket2 

`     |
1253 |             imr_multiaddr: sys::to_in_addr(multiaddr),
     |                                 ^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `to_in_addr` in module `sys`
    --> src/socket.rs:1254:33
     |
1254 |             imr_interface: sys::to_in_addr(interface),
     |                                 ^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IPPROTO_IP` in module `sys`
    --> src/socket.rs:1259:22
     |
1259 |                 sys::IPPROTO_IP,
     |                      ^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IP_DROP_MEMBERSHIP` in module `sys`
    --> src/socket.rs:1260:22
     |
1260 |                 sys::IP_DROP_MEMBERSHIP,
     |                      ^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `to_mreqn` in module `sys``

**Comment by orao-dev1** [comment]
Can you provide more code to see the context? From what you posted this seems like an error in your environment.

**Comment by Merrick17** [comment]
@orao-dev1  sorry just saw the email , I dropped the project was trying to build a guessing game following some instructions while learning solana/Anchor.
I've couldn't even compile first init code 
using ubuntu 18.04 on a VM 
using solana 1.18.18
Anchor 0.30.1 
hopefully this helps

**Comment by orao-dev1** [comment]
The reason why you couldn't compile anything is the environent. Make sure you can actually compile Anchor programs, use Anchor 0.29, not 0.30.x.

For a guessing game maybe you could follow this tutorial:
https://github.com/ddm50/solana-coinflip-game
It uses this VRF and goes through the on-chain program and off-chain client step by step.
