### ISSUE TITLE
randomness fullfilled error

### ISSUE THREAD

**Issue by mihai22622** [orao-network/solana-vrf#2]
Version: orao-network/solana-vrf 0.2.1

The orao vrf documentation states that `randomAcc.fulfilled()` returns the randomness if fulfilled
`      
var randomAcc = undefined;

        try {
          randomAcc = await vrf.getRandomness(gen_seed.publicKey.toBytes());
          console.log(randomAcc);

        } catch (err) {
          toast.notify(`${err.message}`, { type: "error" });

        }
      
      var randomness = randomAcc.fulfilled();

      if (randomness === null) {
        console.log("Randomness is not yet fulfilled " + i);
      } else {
        console.log("Randomness is " + randomness);
        return;
      }`

i keep receiving  the following error indicating the 'fulfilled()' function. Error says TypeError: Argument must be a Buffer

I mention that when executing tests on the anchor env it works. But in this case i have a nextjs + react app

**Comment by mihai22622** [comment]
<img width="725" alt="Screenshot 2022-08-20 at 14 15 04" src="https://user-images.githubusercontent.com/58340360/185746556-71c07ac6-811b-49cb-ad25-c95bc4038a43.png">

**Comment by mihai22622** [comment]
<img width="540" alt="Screenshot 2022-08-20 at 15 38 46" src="https://user-images.githubusercontent.com/58340360/185746579-2b321103-acc6-4a32-8dd3-111cc5797b33.png">

**Comment by anilaravindv** [comment]
I get the same error , so I replaced "randomAcc.fulfilled()" with "randomnessAcc.randomness.every(item => item === 0)" and wait for the randomness to get fulfilled in a loop with some delay.

**Comment by mihai22622** [comment]
thank you @anilaravindv 💯  it works now

**Comment by orao-dev1** [comment]
> I get the same error , so I replaced "randomAcc.fulfilled()" with "randomnessAcc.randomness.every(item => item === 0)" and wait for the randomness to get fulfilled in a loop with some delay.

Due to the nature of blockchains we need to wait for transaction finality.
