### ISSUE TITLE
Error: Account does not exist

### ISSUE THREAD

**Issue by anilaravindv** [orao-network/solana-vrf#3]
Hi , when I request for randomness , this error Error: Account does not exist <"some address"> after fee debit from my account.

Please help , as this is happening on mainnet

**Comment by orao-dev1** [comment]
This is an issue from Solana's RPC. Sometimes the RPC reports the account as missing even though the TX that created it was just reported as finalized - it seems Solana RPC data is stale at that point.
The TX you reported over our TG channel completed successfully - randomness was fulfilled.

**Comment by anilaravindv** [comment]
That makes sense . I can see the account gets created on Solscan but not able to fetch account through RPC.
