### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by rocalex** [orao-network/solana-vrf#4]
When I import js library via npm in my nextjs app, I got an error.
```
./node_modules/@orao-network/solana-vrf/dist/index.js:18:0
Module not found: Can't resolve 'tweetnacl'
```

**Comment by orao-dev1** [comment]
Fixed in [#944c6a7](https://github.com/orao-network/solana-vrf/commit/944c6a744a04ec346e455a8d1019a8013b336214). Please use the latest lib version 0.2.3.
Closing this as fixed.
