### ISSUE TITLE
custom program error: 0x1004

### ISSUE THREAD

**Issue by jvaleskadevs** [orao-network/solana-vrf#5]
Hi!

I deployed the program to my own program_id, 
but when I'm trying to play using the CLI I'm getting an Error,
state command is working well.
how to solve it? 
Thanks.

Command:
`cargo run -q --package roulette-cli -- play`

Output:

> Loading a bullet and spinning the cylinder..
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1004 [4 log messages]
Caused by:
    0: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1004 [4 log messages]
    1: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1004 [4 log messages]

Expected Output:
> -- Using RPC https://api.devnet.solana.com, keypair <PATH_TO_MY_KEYPAIR> -- ------
Loading a bullet and spinning the cylinder..
Waiting for the round to finish..
CLICK! Player <MY_PUBLIC_KEY> is alive after 1 round(s)

Command:
`cargo run -q --package roulette-cli -- state`

Output == Expected Output:
> -- Using RPC https://api.devnet.solana.com, keypair <PATH_TO_MY_KEYPAIR> -- ------
Player <MY_PUBLIC_KEY> has never played

**Comment by orao-dev1** [comment]
Hi.
Have you checked if your deployed program_id is the same as the one specified in lib.rs? This looks like [DeclaredProgramIdMismatch](https://github.com/coral-xyz/anchor/blob/master/lang/src/error.rs#L196) error.

**Comment by orao-dev1** [comment]
Closing this issue as the error is on your end
