### ISSUE TITLE
Account does not exist or has no data

### ISSUE THREAD

**Issue by microgift** [orao-network/solana-vrf#7]
` const vrf = new Orao(provider);

    let force = Buffer.from(Keypair.generate().publicKey.toBuffer());
    const [seed, tx] = await (await vrf.request(force)).rpc()

    const randomness = await vrf.waitFulfilled(force);
    console.log("Your randomness is " + randomness.fulfilled());`
    
I tried to get random number but the error says
Error: Account does not exist or has no data <random account address>

So, I tried to change the commitment of vrf.waitFulfilled(force); to confirmed but it doesn't respond for hours.

**Comment by orao-dev1** [comment]
Marking this as closed. User found the problem in his code and fixed it.

**Comment by microgift** [comment]
> Marking this as closed. User found the problem in his code and fixed it.

Sorry, but I couldn't find the problem in my code.
So I removed waitFulfilled() function calls and rather made my program to sleep for a few seconds.
