### ISSUE TITLE
Projects using this SDK

### ISSUE THREAD

**Issue by luislucena16** [orao-network/solana-vrf#8]
hey guys @great9 @orao-dev1 do you know which projects are currently using this SDK? or any examples/visual tutorials I can see? thanks in advance!

**Comment by great9** [comment]
[ZKVerse](https://x.com/ZKVerseNFT?s=09) is one of our latest client using out vrf on solana. We've made some behind-the-scenes upgrades to lower the randomness fulfillment time.

**Comment by luislucena16** [comment]
nice! sounds good! are there any other examples?
